// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF5IDmamC_aVNaz0gcyvAMlDG8uYVGhVQ',
    appId: '1:907246137493:web:cad30590c775a9bee36b9c',
    messagingSenderId: '907246137493',
    projectId: 'fir-flutter-codelab-99afe',
    authDomain: 'fir-flutter-codelab-99afe.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-99afe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCuvdJjoT4weiqvvUw2_KyFrrAlQmwB4k',
    appId: '1:907246137493:android:85a4e44960563a46e36b9c',
    messagingSenderId: '907246137493',
    projectId: 'fir-flutter-codelab-99afe',
    storageBucket: 'fir-flutter-codelab-99afe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRkhr2VFIkBY-s1OVsl4ryu-HlE4RzWs8',
    appId: '1:907246137493:ios:68a6f5516e680332e36b9c',
    messagingSenderId: '907246137493',
    projectId: 'fir-flutter-codelab-99afe',
    storageBucket: 'fir-flutter-codelab-99afe.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRkhr2VFIkBY-s1OVsl4ryu-HlE4RzWs8',
    appId: '1:907246137493:ios:68a6f5516e680332e36b9c',
    messagingSenderId: '907246137493',
    projectId: 'fir-flutter-codelab-99afe',
    storageBucket: 'fir-flutter-codelab-99afe.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

}